# ============================================================
# Antonela Art Salon - Configuracion de la aplicacion
# ============================================================

# Servidor
server.port=8080

# Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/antonela_art_salon
spring.datasource.username=postgres
spring.datasource.password=jair
spring.datasource.driver-class-name=org.postgresql.Driver


# Esto nos permite solo validar las tablas si estan en la base de datos y de ver tadas las consultas que se hacen asi mismo
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true



# JWT
app.jwt.secret=AntonelaArtSalonSecretKeyForJWT2026Security
app.jwt.expiration-ms=86400000

# Jackson
spring.jackson.serialization.fail-on-empty-beans=false

# CORS
app.cors.allowed-origins=http://localhost:3000

# Stripe
stripe.secret-key=sk_test_xxxxxxxxxxxxxxxxxxxx
stripe.webhook-secret=whsec_xxxxxxxxxxxxxxxxxxxx
stripe.success-url=http://localhost:3000/pago-exitoso
stripe.cancel-url=http://localhost:3000/carrito
